name: socialfy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_storage: ^11.2.4
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  line_awesome_flutter: ^2.0.0
  community_material_icon: ^5.9.55
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_local_notifications: ^15.0.1
  flutter_native_splash: ^2.3.1
  permission_handler: ^10.4.1
  go_router: ^9.0.1
  intl: any
  photo_gallery: ^2.0.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: any
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/socialfy_icon.png
  adaptive_icon_background: "#FFFFFFF"
  adaptive_icon_forground: assets/images/mo3tv.png
flutter_native_splash:
  image: assets/images/splash_logo_dark.png
  color: "#ffffff"
  color_dark: "#000000"
  image_dark: assets/images/splash_logo.png




flutter:
  uses-material-design: true

  assets:
     - assets/images/
  fonts:
    - family: AppLogo
      fonts:
        - asset: assets/icons/AppLogo.ttf
    - family: Comment
      fonts:
        - asset: assets/icons/Comment.ttf
    - family: PaperPlane
      fonts:
        - asset: assets/icons/PaperPlane.ttf
    - family: Paper
      fonts:
        - asset: assets/icons/Paper.ttf
    - family: Theme
      fonts:
        - asset: assets/icons/Theme.ttf
    - family: billabong
      fonts:
        - asset: assets/fonts/billabong/Billabong.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
