name: socialfy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_storage: ^10.3.11
  cached_network_image: ^3.2.2
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  fluttertoast: ^8.0.9
  image_picker: ^0.8.6
  shimmer: ^2.0.0
  line_awesome_flutter: ^2.0.0
  community_material_icon: ^5.9.55
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.1.0+1
  get_it: ^7.2.0
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
#  scrollable_positioned_list: ^0.3.5
  flutter_storage_path: ^1.0.4
  flutter_local_notifications: ^12.0.2
  firebase_messaging: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/socialfy_logo.png
     - assets/images/image_1.jpg
     - assets/images/image_2.jpg


  fonts:
    - family: AppLogo
      fonts:
        - asset: assets/icons/AppLogo.ttf
    - family: Comment
      fonts:
        - asset: assets/icons/Comment.ttf
    - family: PaperPlane
      fonts:
        - asset: assets/icons/PaperPlane.ttf
    - family: Paper
      fonts:
        - asset: assets/icons/Paper.ttf
    - family: Theme
      fonts:
        - asset: assets/icons/Theme.ttf
    - family: billabong
      fonts:
        - asset: assets/fonts/billabong/Billabong.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
